# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './windows/layouts/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_paintBox = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_paintBox.setStyleSheet("background-color: #dddddd")
        self.dockWidget_paintBox.setObjectName("dockWidget_paintBox")
        self.dockWidgetContents_paintBox = QtWidgets.QWidget()
        self.dockWidgetContents_paintBox.setObjectName("dockWidgetContents_paintBox")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_paintBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dockWidget_paintBox.setWidget(self.dockWidgetContents_paintBox)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_paintBox)
        self.dockWidget_behaviorControl = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_behaviorControl.setStyleSheet("background-color: #dddddd;")
        self.dockWidget_behaviorControl.setObjectName("dockWidget_behaviorControl")
        self.dockWidgetContents_behaviorControl = QtWidgets.QWidget()
        self.dockWidgetContents_behaviorControl.setObjectName("dockWidgetContents_behaviorControl")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_behaviorControl)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_ctrlEnabled = QtWidgets.QCheckBox(self.dockWidgetContents_behaviorControl)
        self.checkBox_ctrlEnabled.setObjectName("checkBox_ctrlEnabled")
        self.verticalLayout.addWidget(self.checkBox_ctrlEnabled)
        self.checkBox_intersectedSeletion = QtWidgets.QCheckBox(self.dockWidgetContents_behaviorControl)
        self.checkBox_intersectedSeletion.setObjectName("checkBox_intersectedSeletion")
        self.verticalLayout.addWidget(self.checkBox_intersectedSeletion)
        self.dockWidget_behaviorControl.setWidget(self.dockWidgetContents_behaviorControl)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_behaviorControl)
        self.dockWidget_paintBox.raise_()
        self.dockWidget_behaviorControl.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dockWidget_paintBox.setWindowTitle(_translate("MainWindow", "Paint Box"))
        self.dockWidget_behaviorControl.setWindowTitle(_translate("MainWindow", "Behavior Control"))
        self.checkBox_ctrlEnabled.setText(_translate("MainWindow", "Отслеживание кнопки Ctrl"))
        self.checkBox_intersectedSeletion.setText(_translate("MainWindow", "Выделять всех в пересечении"))
